
export const HANDLER_IDS = {
  //회원가입.로그인
  REGISTEREQUST: 1,
  REGISTERESPONSE: 2,
  LOGINREQUEST: 3,
  LOGINRESPONSE: 4,

  //매칭
  MATCHREQUST: 5,
  MATCHSTARTNOTIFICATION: 6,
  
  //상태 동기화
  STATESYNCNOTIFICATION: 7,

  // 타워 구입 및 배치
  TOWERPURCHASEREQUST: 8,
  TOWERPURCHASERESPONSE: 9,
  ADDENEMYTOWERNOTIFICATION: 10,

  // 몬스터 생성
  SPAWNMONSTERREQUST: 11,
  SPAWNMONSTERRESPONSE: 12,
  SPAWNMONSTERNOTIFICATION: 13,

  // 전투 액션
  TOWERATTACKREQUST: 14,
  ENEMYTOWERATTACKNOTIFICATION: 15,
  MONSTERATTACKBASEREQUST: 16,

  // 기지 HP 업데이트 및 게임 오버
  UPDATEBASEHPNOTIFICATION: 17,
  GAMEOVERNOTIFICATION: 18,

  // 게임 종료  
  GAMEENDREQUST: 19,

  // 몬스터 사망 통지
  MONSTERDEATHNOTIFICATION: 20,
  ENEMYMONSTERDEATHNOTIFICATION: 21,
};